name: Build Windows Installer

on:
  push:
    branches: [production]
  pull_request:
    branches: [production]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup vcpkg
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat

      - name: Install build dependencies
        run: |
          vcpkg install --triplet x64-windows
          choco install nsis

      - name: Set environment variables
        run: |
          echo "CMAKE_PREFIX_PATH=D:/a/QTDecisionMaker/QTDecisionMaker/vcpkg/installed/x64-windows/share/qt6" >> $env:GITHUB_ENV
          echo "VCPKG_ROOT=D:/a/QTDecisionMaker/QTDecisionMaker/vcpkg" >> $env:GITHUB_ENV

      - name: Configure and build
        run: |
          $toolchainPath = Join-Path -Path $env:VCPKG_ROOT -ChildPath "scripts/buildsystems/vcpkg.cmake"
          cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE="$toolchainPath"
          cmake --build build --config Release

      - name: Prepare dist directory
        run: |
          mkdir dist
          copy build\Release\QTDecisionMaker.exe dist\

      - name: Install build
        run: |
          cmake --install build --config Release --prefix dist

      - name: Create installer
        run: |
          cd build
          makensis ../installer.nsi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: D:\a\QTDecisionMaker\QTDecisionMaker\DecisionMaker_Installer.exe
          if-no-files-found: 'error'