name: Build and Upload Executables (Linux & Windows)

on:
  push:
    branches: [ "Production" ]
  pull_request:
    branches: [ "Production" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Qt (Linux)
      if: matrix.os == 'ubuntu-latest'
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.0' # Change as needed

    - name: Install dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake qt6-base-dev

    - name: Set up MSVC (Windows)
      if: matrix.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Set up Qt (Windows)
      if: matrix.os == 'windows-latest'
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.0' # Change as needed

    - name: Configure CMake
      run: >
        cmake -B build
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S .
      env:
        CC: ${{ matrix.os == 'ubuntu-latest' && 'gcc' || '' }}
        CXX: ${{ matrix.os == 'ubuntu-latest' && 'g++' || '' }}

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Find Executable (Linux)
      if: matrix.os == 'ubuntu-latest'
      id: find_exe_linux
      run: |
        # Try to find the main executable (change DecisionMaker if needed)
        exe=$(find build -type f -executable -name DecisionMaker | head -n 1)
        echo "exe_path=$exe" >> $GITHUB_OUTPUT

    - name: Find Executable (Windows)
      if: matrix.os == 'windows-latest'
      id: find_exe_win
      shell: pwsh
      run: |
        $exe = Get-ChildItem -Path build -Recurse -Filter DecisionMaker.exe | Select-Object -First 1
        echo "exe_path=$($exe.FullName)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

    - name: Upload Linux Executable
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: linux-executable
        path: ${{ steps.find_exe_linux.outputs.exe_path }}

    - name: Upload Windows Executable
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: ${{ steps.find_exe_win.outputs.exe_path }}
