name: Build Windows Installer

on:
  push:
    branches: [production]
  pull_request:
    branches: [production]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.9.0'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          cache: 'true'
          setup-python: 'false'

      - name: Install NSIS
        run: choco install nsis

      - name: Configure and build
        run: |
          cmake -S . -B build
          cmake --build build --config Release

      - name: Prepare dist directory
        run: |
          mkdir -p dist
          Copy-Item build\Release\QTDecisionMaker.exe -Destination dist\

      - name: Deploy Qt dependencies
        run: |
          windeployqt dist\QTDecisionMaker.exe --release --no-translations --no-system-d3d-compiler

      - name: Install build
        run: |
          cmake --install build --config Release --prefix dist

      - name: Debug - List files in dist
        run: |
          Get-ChildItem -Path dist -Recurse | ForEach-Object { Write-Host $_.FullName }

      - name: Create installer
        run: |
          cd build
          makensis ../installer.nsi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: D:\a\QTDecisionMaker\QTDecisionMaker\DecisionMaker_Installer.exe
          if-no-files-found: 'error'

      - name: Upload dist directory (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: dist-directory-contents
          path: dist
          if-no-files-found: 'warn'
